/**
 * Maps a country's GeoJSON `name` (the same English name used as the key in
 * `booksByCountry` and as values in FRENCH_TO_GEOJSON_NAME) to one of 5
 * regions, used to group the country filter dropdown by continent.
 *
 * Scoped to exactly the countries listed in FRENCH_TO_GEOJSON_NAME — add an
 * entry here whenever a new country is added there.
 */
export type ContinentName = "Afrique" | "Amériques" | "Asie" | "Europe" | "Océanie";

export const CONTINENT_ORDER: ContinentName[] = ["Afrique", "Amériques", "Asie", "Europe", "Océanie"];

export const GEONAME_TO_CONTINENT: Record<string, ContinentName> = {
  "Afghanistan": "Asie",
  "South Africa": "Afrique",
  "Albania": "Europe",
  "Algeria": "Afrique",
  "Germany": "Europe",
  "Andorra": "Europe",
  "Angola": "Afrique",
  "Saudi Arabia": "Asie",
  "Argentina": "Amériques",
  "Armenia": "Asie",
  "Australia": "Océanie",
  "Austria": "Europe",
  "Azerbaijan": "Asie",
  "Bangladesh": "Asie",
  "Belgium": "Europe",
  "Benin": "Afrique",
  "Belarus": "Europe",
  "Bolivia": "Amériques",
  "Bosnia and Herzegovina": "Europe",
  "Botswana": "Afrique",
  "Brazil": "Amériques",
  "Bulgaria": "Europe",
  "Burkina Faso": "Afrique",
  "Burundi": "Afrique",
  "Cambodia": "Asie",
  "Cameroon": "Afrique",
  "Canada": "Amériques",
  "Chile": "Amériques",
  "China": "Asie",
  "Cyprus": "Europe",
  "Colombia": "Amériques",
  "Republic of the Congo": "Afrique",
  "North Korea": "Asie",
  "South Korea": "Asie",
  "Costa Rica": "Amériques",
  "Ivory Coast": "Afrique",
  "Croatia": "Europe",
  "Cuba": "Amériques",
  "Denmark": "Europe",
  "Egypt": "Afrique",
  "United Arab Emirates": "Asie",
  "Ecuador": "Amériques",
  "Eritrea": "Afrique",
  "Spain": "Europe",
  "Estonia": "Europe",
  "United States of America": "Amériques",
  "Ethiopia": "Afrique",
  "Finland": "Europe",
  "France": "Europe",
  "Gabon": "Afrique",
  "Gambia": "Afrique",
  "Georgia": "Asie",
  "Ghana": "Afrique",
  "Greece": "Europe",
  "Greenland": "Amériques",
  "Guatemala": "Amériques",
  "Guinea": "Afrique",
  "Guyana": "Amériques",
  "Haiti": "Amériques",
  "Honduras": "Amériques",
  "Hungary": "Europe",
  "India": "Asie",
  "Indonesia": "Asie",
  "Iraq": "Asie",
  "Iran": "Asie",
  "Ireland": "Europe",
  "Iceland": "Europe",
  "Israel": "Asie",
  "Italy": "Europe",
  "Jamaica": "Amériques",
  "Japan": "Asie",
  "Jordan": "Asie",
  "Kazakhstan": "Asie",
  "Kenya": "Afrique",
  "Kyrgyzstan": "Asie",
  "Kosovo": "Europe",
  "Kuwait": "Asie",
  "Laos": "Asie",
  "Lesotho": "Afrique",
  "Latvia": "Europe",
  "Lebanon": "Asie",
  "Liberia": "Afrique",
  "Libya": "Afrique",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Macedonia": "Europe",
  "Madagascar": "Afrique",
  "Malaysia": "Asie",
  "Malawi": "Afrique",
  "Mali": "Afrique",
  "Malta": "Europe",
  "Morocco": "Afrique",
  "Mauritania": "Afrique",
  "Mexico": "Amériques",
  "Moldova": "Europe",
  "Mongolia": "Asie",
  "Montenegro": "Europe",
  "Mozambique": "Afrique",
  "Myanmar": "Asie",
  "Namibia": "Afrique",
  "Nepal": "Asie",
  "Nicaragua": "Amériques",
  "Niger": "Afrique",
  "Nigeria": "Afrique",
  "Norway": "Europe",
  "New Zealand": "Océanie",
  "Oman": "Asie",
  "Uganda": "Afrique",
  "Uzbekistan": "Asie",
  "Pakistan": "Asie",
  "West Bank": "Asie",
  "Panama": "Amériques",
  "Papua New Guinea": "Océanie",
  "Paraguay": "Amériques",
  "Netherlands": "Europe",
  "Peru": "Amériques",
  "Philippines": "Asie",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Qatar": "Asie",
  "Central African Republic": "Afrique",
  "Democratic Republic of the Congo": "Afrique",
  "Dominican Republic": "Amériques",
  "Czech Republic": "Europe",
  "Romania": "Europe",
  "United Kingdom": "Europe",
  "Russia": "Europe",
  "Rwanda": "Afrique",
  "Senegal": "Afrique",
  "Republic of Serbia": "Europe",
  "Sierra Leone": "Afrique",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Somalia": "Afrique",
  "Sudan": "Afrique",
  "South Sudan": "Afrique",
  "Sri Lanka": "Asie",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Suriname": "Amériques",
  "Syria": "Asie",
  "Taiwan": "Asie",
  "Tajikistan": "Asie",
  "United Republic of Tanzania": "Afrique",
  "Chad": "Afrique",
  "Thailand": "Asie",
  "East Timor": "Asie",
  "Togo": "Afrique",
  "Trinidad and Tobago": "Amériques",
  "Tunisia": "Afrique",
  "Turkmenistan": "Asie",
  "Turkey": "Europe",
  "Ukraine": "Europe",
  "Uruguay": "Amériques",
  "Venezuela": "Amériques",
  "Vietnam": "Asie",
  "Yemen": "Asie",
  "Zambia": "Afrique",
  "Zimbabwe": "Afrique",
};

export function lookupContinent(geoName: string): ContinentName | undefined {
  return GEONAME_TO_CONTINENT[geoName];
}
