/**
 * Maps a country name as written in a book's "Pays:" field (French) to the
 * "name" property used by the bundled data/world-countries.geo.json dataset
 * (derived from Natural Earth, English names, some pre-2019 naming e.g.
 * "Macedonia", "Swaziland", "United Republic of Tanzania").
 *
 * Not every country the club could ever mention is guaranteed to be listed
 * here yet — add entries as new "Pays:" values show up in books/*.md.
 */
export const FRENCH_TO_GEOJSON_NAME: Record<string, string> = {
  "Afghanistan": "Afghanistan",
  "Afrique du Sud": "South Africa",
  "Albanie": "Albania",
  "Algérie": "Algeria",
  "Allemagne": "Germany",
  "Andorre": "Andorra",
  "Angola": "Angola",
  "Arabie Saoudite": "Saudi Arabia",
  "Argentine": "Argentina",
  "Arménie": "Armenia",
  "Australie": "Australia",
  "Autriche": "Austria",
  "Azerbaïdjan": "Azerbaijan",
  "Bangladesh": "Bangladesh",
  "Belgique": "Belgium",
  "Bénin": "Benin",
  "Biélorussie": "Belarus",
  "Bolivie": "Bolivia",
  "Bosnie-Herzégovine": "Bosnia and Herzegovina",
  "Botswana": "Botswana",
  "Brésil": "Brazil",
  "Bulgarie": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cambodge": "Cambodia",
  "Cameroun": "Cameroon",
  "Canada": "Canada",
  "Chili": "Chile",
  "Chine": "China",
  "Chypre": "Cyprus",
  "Colombie": "Colombia",
  "Congo": "Republic of the Congo",
  "Corée du Nord": "North Korea",
  "Corée du Sud": "South Korea",
  "Costa Rica": "Costa Rica",
  "Côte d'Ivoire": "Ivory Coast",
  "Croatie": "Croatia",
  "Cuba": "Cuba",
  "Danemark": "Denmark",
  "Égypte": "Egypt",
  "Émirats Arabes Unis": "United Arab Emirates",
  "Équateur": "Ecuador",
  "Érythrée": "Eritrea",
  "Espagne": "Spain",
  "Estonie": "Estonia",
  "États-Unis": "United States of America",
  "Éthiopie": "Ethiopia",
  "Finlande": "Finland",
  "France": "France",
  "Gabon": "Gabon",
  "Gambie": "Gambia",
  "Géorgie": "Georgia",
  "Ghana": "Ghana",
  "Grèce": "Greece",
  "Groenland": "Greenland",
  "Guatemala": "Guatemala",
  "Guinée": "Guinea",
  "Guyana": "Guyana",
  "Haïti": "Haiti",
  "Honduras": "Honduras",
  "Hongrie": "Hungary",
  "Inde": "India",
  "Indonésie": "Indonesia",
  "Irak": "Iraq",
  "Iran": "Iran",
  "Irlande": "Ireland",
  "Islande": "Iceland",
  "Israël": "Israel",
  "Italie": "Italy",
  "Jamaïque": "Jamaica",
  "Japon": "Japan",
  "Jordanie": "Jordan",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kirghizistan": "Kyrgyzstan",
  "Kosovo": "Kosovo",
  "Koweït": "Kuwait",
  "Laos": "Laos",
  "Lesotho": "Lesotho",
  "Lettonie": "Latvia",
  "Liban": "Lebanon",
  "Liberia": "Liberia",
  "Libye": "Libya",
  "Lituanie": "Lithuania",
  "Luxembourg": "Luxembourg",
  "Macédoine du Nord": "Macedonia",
  "Madagascar": "Madagascar",
  "Malaisie": "Malaysia",
  "Malawi": "Malawi",
  "Mali": "Mali",
  "Malte": "Malta",
  "Maroc": "Morocco",
  "Mauritanie": "Mauritania",
  "Mexique": "Mexico",
  "Moldavie": "Moldova",
  "Mongolie": "Mongolia",
  "Monténégro": "Montenegro",
  "Mozambique": "Mozambique",
  "Myanmar": "Myanmar",
  "Namibie": "Namibia",
  "Népal": "Nepal",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "Norvège": "Norway",
  "Nouvelle-Zélande": "New Zealand",
  "Oman": "Oman",
  "Ouganda": "Uganda",
  "Ouzbékistan": "Uzbekistan",
  "Pakistan": "Pakistan",
  "Palestine": "West Bank",
  "Panama": "Panama",
  "Papouasie-Nouvelle-Guinée": "Papua New Guinea",
  "Paraguay": "Paraguay",
  "Pays-Bas": "Netherlands",
  "Pérou": "Peru",
  "Philippines": "Philippines",
  "Pologne": "Poland",
  "Portugal": "Portugal",
  "Qatar": "Qatar",
  "République Centrafricaine": "Central African Republic",
  "République Démocratique du Congo": "Democratic Republic of the Congo",
  "République Dominicaine": "Dominican Republic",
  "République Tchèque": "Czech Republic",
  "Roumanie": "Romania",
  "Royaume-Uni": "United Kingdom",
  "Russie": "Russia",
  "Rwanda": "Rwanda",
  "Sénégal": "Senegal",
  "Serbie": "Republic of Serbia",
  "Sierra Leone": "Sierra Leone",
  "Slovaquie": "Slovakia",
  "Slovénie": "Slovenia",
  "Somalie": "Somalia",
  "Soudan": "Sudan",
  "Soudan du Sud": "South Sudan",
  "Sri Lanka": "Sri Lanka",
  "Suède": "Sweden",
  "Suisse": "Switzerland",
  "Suriname": "Suriname",
  "Syrie": "Syria",
  "Taïwan": "Taiwan",
  "Tadjikistan": "Tajikistan",
  "Tanzanie": "United Republic of Tanzania",
  "Tchad": "Chad",
  "Thaïlande": "Thailand",
  "Timor Oriental": "East Timor",
  "Togo": "Togo",
  "Trinité-et-Tobago": "Trinidad and Tobago",
  "Tunisie": "Tunisia",
  "Turkménistan": "Turkmenistan",
  "Turquie": "Turkey",
  "Ukraine": "Ukraine",
  "Uruguay": "Uruguay",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Yémen": "Yemen",
  "Zambie": "Zambia",
  "Zimbabwe": "Zimbabwe",
};

/** Historical countries that no longer appear in modern boundary data.
 * When "Pays:" holds one of these, pick the modern successor state that
 * matches the author's actual birthplace when filling it in by hand —
 * there's no single correct automatic mapping. */
export const KNOWN_UNMAPPABLE = new Set([
  "Yougoslavie",
  "URSS",
  "Tchécoslovaquie",
]);

export function lookupCountryGeoName(frenchName: string): string | undefined {
  const trimmed = frenchName.trim();
  return FRENCH_TO_GEOJSON_NAME[trimmed];
}
